"""Power by blocked simulation, not by rescaling a selected t-statistic.

The earlier power figure took the largest |t| over a family of searched targets and scaled
it by sqrt(n). That number is the winner's curse expressed as an effect size: the maximum of
many noisy statistics is biased upward by construction, so the implied sample size is an
optimistic bound rather than an estimate, and it gets *more* optimistic the more targets
were searched.

This module replaces it. The estimand, the score, the sign and the effect are frozen before
any simulation runs; the effect is shrunk for selection; and the null is generated by
resampling whole blocks of sessions from the observed data, so the simulated series inherits
the serial dependence and the fat tails that an i.i.d. draw would discard.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Final

import numpy as np
import numpy.typing as npt

type FloatArray = npt.NDArray[np.float64]

DEFAULT_REPETITIONS: Final = 2000
DEFAULT_BLOCK_LENGTH: Final = 5


@dataclass(frozen=True, slots=True)
class FrozenDesign:
    """Everything that must be fixed before a power number means anything."""

    target: str
    score: str
    sign: int
    effect: float
    alpha_one_sided: float
    selection_candidates: int

    def __post_init__(self) -> None:
        if self.sign not in (-1, 1):
            raise ValueError("RP2_POWER_SIGN_INVALID")
        if not 0.0 < self.alpha_one_sided < 0.5:
            raise ValueError("RP2_POWER_ALPHA_INVALID")
        if self.selection_candidates < 1:
            raise ValueError("RP2_POWER_CANDIDATES_INVALID")


def shrink_selected_effect(effect: float, *, candidates: int, standard_error: float) -> float:
    """Shrink an effect that was chosen as the best of ``candidates`` toward zero.

    The expected maximum of ``k`` independent standard normals is about
    ``sqrt(2 ln k)`` standard errors above zero even when every true effect is zero, so an
    effect selected as the winner carries that much upward bias. Subtracting it is a
    deliberately conservative correction, and it is applied to the *magnitude* so the sign
    is never flipped by the adjustment.
    """

    if candidates < 1 or standard_error < 0.0:
        raise ValueError("RP2_POWER_SHRINK_PARAMS_INVALID")
    if candidates == 1 or standard_error == 0.0:
        return effect
    bias = math.sqrt(2.0 * math.log(candidates)) * standard_error
    magnitude = max(abs(effect) - bias, 0.0)
    return math.copysign(magnitude, effect)


@dataclass(frozen=True, slots=True)
class PowerResult:
    """Simulated power for one design at one sample size."""

    sessions: int
    power: float
    rejection_rate_under_null: float
    repetitions: int
    block_length: int


def _blocked_draw(
    values: FloatArray, sessions: int, block_length: int, generator: np.random.Generator
) -> FloatArray:
    """Circular block resample of ``sessions`` observations from ``values``."""

    size = values.size
    blocks = int(np.ceil(sessions / block_length))
    starts = generator.integers(0, size, size=blocks)
    offsets = (starts[:, None] + np.arange(block_length)[None, :]) % size
    return np.asarray(values[offsets.ravel()[:sessions]], dtype=np.float64)


def simulate_power(
    observed_session_scores: FloatArray,
    design: FrozenDesign,
    *,
    sessions: int,
    repetitions: int = DEFAULT_REPETITIONS,
    block_length: int = DEFAULT_BLOCK_LENGTH,
    seed: int = 650,
) -> PowerResult:
    """Power and null rejection rate by resampling whole blocks of observed sessions.

    ``observed_session_scores`` is one score per session under the frozen design, centred by
    this function so that the resampled series carries the observed *dispersion* without
    importing the observed *mean*. The alternative adds the shrunk effect; the null adds
    nothing. Reporting both is the point: a rejection rate far from ``alpha`` under the null
    means the test itself is mis-sized and its power number is meaningless.
    """

    if observed_session_scores.size < 10:
        raise ValueError("RP2_POWER_TOO_FEW_SESSIONS")
    if sessions < 2 or repetitions < 1 or block_length < 1:
        raise ValueError("RP2_POWER_PARAMS_INVALID")

    centred = observed_session_scores - float(np.mean(observed_session_scores))
    generator = np.random.default_rng(seed)
    critical = _normal_quantile(1.0 - design.alpha_one_sided)

    reject_alt = 0
    reject_null = 0
    for _ in range(repetitions):
        noise = _blocked_draw(centred, sessions, block_length, generator)
        spread = float(np.std(noise, ddof=1))
        if spread <= 0.0:
            continue
        standard_error = spread / math.sqrt(sessions)
        null_statistic = design.sign * float(np.mean(noise)) / standard_error
        alt_statistic = design.sign * float(np.mean(noise) + design.effect) / standard_error
        reject_null += int(null_statistic > critical)
        reject_alt += int(alt_statistic > critical)
    return PowerResult(
        sessions=sessions,
        power=reject_alt / repetitions,
        rejection_rate_under_null=reject_null / repetitions,
        repetitions=repetitions,
        block_length=block_length,
    )


def _normal_quantile(probability: float) -> float:
    from scipy import stats

    return float(stats.norm.ppf(probability))


def sessions_for_power(
    observed_session_scores: FloatArray,
    design: FrozenDesign,
    *,
    target_power: float = 0.80,
    candidates: tuple[int, ...] = (30, 60, 90, 120, 180, 240, 360, 540, 750),
    repetitions: int = DEFAULT_REPETITIONS,
    block_length: int = DEFAULT_BLOCK_LENGTH,
    seed: int = 650,
) -> tuple[int | None, list[PowerResult]]:
    """Smallest simulated sample size reaching ``target_power``, plus the whole curve.

    Returns ``None`` when no candidate size reaches the target, which is a more useful
    answer than extrapolating a formula past the range the simulation actually covered.
    """

    curve = [
        simulate_power(
            observed_session_scores,
            design,
            sessions=size,
            repetitions=repetitions,
            block_length=block_length,
            seed=seed,
        )
        for size in candidates
    ]
    for result in curve:
        if result.power >= target_power:
            return result.sessions, curve
    return None, curve
