"""Generate the single machine-readable statement of current project state.

Emits data/CANONICAL_STATE.json and STATUS.md (both AUTO-GENERATED; never edit by
hand). A hermetic CI test regenerates the state and fails on ANY drift, so a
document claiming to be current cannot silently contradict the repository
(decision 63). Regenerate after every substantive change:

    uv run python scripts/generate_canonical_state.py
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
STATE_PATH = REPO / "data" / "CANONICAL_STATE.json"
STATUS_PATH = REPO / "STATUS.md"

AUTHORIZED_SOURCES = (
    "data/FROZEN_ARTIFACTS.json",
    "data/GATED_DATA_POINTERS.json",
    "scripts/_gated_exclude_list.txt",
    ".github/workflows/ci.yml",
    "docs/methodology_decisions.md",
    "docs/model_naming_note_v1.md",
    "docs/ci_contract_v1.md",
    "docs/evidence_immutability_v1.md",
    "docs/provider_license_review_v1.md",
    "artifacts/gate1_inference/results.json",
    "artifacts/mcs_block_sensitivity/results.json",
)

SUPERSEDED_DOCUMENTS = {
    "docs/architecture.md": (
        "pre-pilot boundary description; current state lives in STATUS.md and docs/INDEX.md"
    ),
    "reports/remaining_work_investigation_20260818.md": (
        "point-in-time snapshot from 2026-08-18 morning; thesis prose, hosted test CI and "
        "alerting listed there as missing were delivered the same day — see STATUS.md"
    ),
}


def _sha(path: Path) -> str:
    data = path.read_bytes()
    if path.suffix != ".parquet":
        data = data.replace(b"\r\n", b"\n")
    return hashlib.sha256(data).hexdigest()


def build_state() -> dict[str, Any]:
    """Assemble the canonical state from the authorized sources only."""
    frozen = json.loads((REPO / "data" / "FROZEN_ARTIFACTS.json").read_text(encoding="utf-8"))
    gated = json.loads((REPO / "data" / "GATED_DATA_POINTERS.json").read_text(encoding="utf-8"))
    decisions_text = (REPO / "docs" / "methodology_decisions.md").read_text(encoding="utf-8")
    decision_numbers = [int(match) for match in re.findall(r"^(\d+)\.\s", decisions_text, re.M)]
    return {
        "schema_version": "canonical-state-v1.0",
        "note": (
            "AUTO-GENERATED by scripts/generate_canonical_state.py; never edit by hand. "
            "CI regenerates and fails on drift (decision 63)."
        ),
        "governance": {
            "latest_decision": max(decision_numbers),
            "decision_count": len(decision_numbers),
        },
        "frozen_evidence": {
            "registry": "data/FROZEN_ARTIFACTS.json",
            "artifact_count": len(frozen["entries"]),
            "registry_sha256": _sha(REPO / "data" / "FROZEN_ARTIFACTS.json"),
        },
        "gated_data": {
            "pointer_file": "data/GATED_DATA_POINTERS.json",
            "file_count": len(gated["files"]),
            "storage": gated["storage"],
        },
        "active_protocols": [
            {
                "id": "phase8-one-shot",
                "document": "docs/phase8_one_shot_protocol_v1.md",
                "sha256": _sha(REPO / "docs" / "phase8_one_shot_protocol_v1.md"),
                "state": "frozen; owner authorization gate 2026-08-29",
            },
            {
                "id": "phase9-total-contribution",
                "document": "docs/phase9_total_contribution_protocol_v1.md",
                "sha256": _sha(REPO / "docs" / "phase9_total_contribution_protocol_v1.md"),
                "state": (
                    "frozen; collection active for sessions strictly after 2026-08-18, "
                    "60-session clock, evaluation authorization ~Nov 2026"
                ),
            },
        ],
        "canonical_results": {
            "sources": {
                "studentized_inference": {
                    "path": "artifacts/gate1_inference/results.json",
                    "sha256": _sha(REPO / "artifacts" / "gate1_inference" / "results.json"),
                },
                "mcs_block_sensitivity": {
                    "path": "artifacts/mcs_block_sensitivity/results.json",
                    "sha256": _sha(REPO / "artifacts" / "mcs_block_sensitivity" / "results.json"),
                },
            },
            "headline_claims": [
                "B2-over-B1 activity increment: prospectively null, model-family-bound, "
                "calibration-linked (decisions 48/53); the Gamma family never enters any "
                "canonical Model Confidence Set at any bootstrap block length.",
                "Total option-state contribution (B0 to B2): cross-family positive on the "
                "2024 blocks and both 2025 eras under the uniform ladder, decaying to null "
                "by 2026 (decision 56, EXPLORATORY_DESCRIPTIVE; decay -0.0277/yr).",
                "Registered model name har_rv is a log-linear fixed extension, NOT the "
                "Gate-3 intraday HAR/HARQ (decision 60, docs/model_naming_note_v1.md).",
            ],
        },
        "future_campaigns": [
            "Phase 8 one-shot confirmation (single authorized read, after 2026-08-29)",
            "Phase 9 total-contribution evaluation (after 60 collected sessions, ~Nov 2026)",
        ],
        "ci": {
            "contract": "docs/ci_contract_v1.md",
            "required_checks": ["quality", "hermetic"],
            "coverage_min_percent": 80,
            "tier2_runner": "scripts/run_local_evidence_gates.py",
            "publish_gate": "scripts/publish_mirror.sh refuses to push unless tier-2 passes",
        },
        "superseded_documents": [
            {"path": path, "why": why} for path, why in sorted(SUPERSEDED_DOCUMENTS.items())
        ],
        "authorized_sources": {
            source: _sha(REPO / source) for source in AUTHORIZED_SOURCES
        },
    }


def render_status(state: dict[str, Any]) -> str:
    """Human-readable rendering of the same state."""
    lines = [
        "# STATUS — canonical project state",
        "",
        "> AUTO-GENERATED from `data/CANONICAL_STATE.json` by",
        "> `scripts/generate_canonical_state.py`. Never edit by hand; CI fails on drift.",
        "> This file supersedes any narrative document that disagrees with it.",
        "",
        f"- Governance: decision {state['governance']['latest_decision']} is the latest "
        f"({state['governance']['decision_count']} recorded).",
        f"- Frozen evidence: {state['frozen_evidence']['artifact_count']} artifacts pinned in "
        "`data/FROZEN_ARTIFACTS.json` (physical tripwire on every CI run).",
        f"- Gated data: {state['gated_data']['file_count']} files in private storage "
        "(`data/GATED_DATA_POINTERS.json`).",
        "",
        "## Active protocols",
        "",
    ]
    for protocol in state["active_protocols"]:
        lines.append(f"- **{protocol['id']}** — `{protocol['document']}`: {protocol['state']}")
    lines += ["", "## Canonical results (citation rule: decision 53)", ""]
    for claim in state["canonical_results"]["headline_claims"]:
        lines.append(f"- {claim}")
    lines += ["", "## Future campaigns", ""]
    for campaign in state["future_campaigns"]:
        lines.append(f"- {campaign}")
    lines += [
        "",
        "## CI",
        "",
        f"- Required checks: {', '.join(state['ci']['required_checks'])} "
        f"(coverage >= {state['ci']['coverage_min_percent']}%).",
        f"- Tier 2 (licensed evidence): `{state['ci']['tier2_runner']}`; "
        f"{state['ci']['publish_gate']}.",
        "",
        "## Superseded documents (do not cite as current)",
        "",
    ]
    for doc in state["superseded_documents"]:
        lines.append(f"- `{doc['path']}` — {doc['why']}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    state = build_state()
    STATE_PATH.write_text(
        json.dumps(state, indent=1, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )
    STATUS_PATH.write_text(render_status(state), encoding="utf-8", newline="\n")
    commit = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True, cwd=REPO
    ).stdout.strip()
    print(f"[state] wrote {STATE_PATH.name} + STATUS.md (at commit {commit})")


if __name__ == "__main__":
    main()
